### ISSUE TITLE
GraphQL TypeError: String cannot represent value: {} error in Link elements

### ISSUE THREAD

**Issue by hades200082** [prismicio/prismic-gatsby#284]
When querying any documents that have a "Link" element in them I get this error if the `url` property of the link is included in the GraphQL query.

```
"TypeError: String cannot represent value: {}",
        "    at GraphQLScalarType.serializeString [as serialize] (D:\\Projects\\Personal\\Gitlab\\my-website\\node_modules\\graphql\\type\\scalars.js:159:9)",
        "    at completeLeafValue (D:\\Projects\\Personal\\Gitlab\\my-website\\node_modules\\graphql\\execution\\execute.js:635:37)",
        "    at completeValue (D:\\Projects\\Personal\\Gitlab\\my-website\\node_modules\\graphql\\execution\\execute.js:579:12)",
        "    at D:\\Projects\\Personal\\Gitlab\\my-website\\node_modules\\graphql\\execution\\execute.js:492:16",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "    at async Promise.all (index 4)",
        "    at async Promise.all (index 1)",
        "    at async Promise.all (index 2)",
        "    at async Promise.all (index 1)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)"
```

**Eaxample query**

```
query MyQuery {
  allPrismicPage {
    nodes {
      uid
      type
      data {
        cta_text
        cta_link {
          link_type
          uid
          target
          type
          url
        }
      }
    }
  }
}
```

**Example page type schema**

```
{
  "Main": {
    "title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1",
        "label": "Title"
      }
    },
    "header_type": {
      "type": "Select",
      "config": {
        "options": [
          "Standard",
          "Section",
          "Hero",
          "Video"
        ],
        "default_value": "Standard",
        "label": "Header type"
      }
    },
    "header_text": {
      "type": "Text",
      "config": {
        "label": "Header text"
      }
    },
    "header_image": {
      "type": "Image",
      "config": {
        "constraint": {
          "width": 2000
        },
        "thumbnails": [
          {
            "name": "Banner",
            "width": 2000,
            "height": 600
          },
          {
            "name": "Social",
            "width": 1200,
            "height": 628
          }
        ],
        "label": "Header image"
      }
    },
    "cta_text": {
      "type": "Text",
      "config": {
        "label": "CTA Text"
      }
    },
    "cta_link": {
      "type": "Link",
      "config": {
        "allowTargetBlank": true,
        "label": "CTA Link"
      }
    },
    "body": {
      "type": "Slices",
      "fieldset": "Slice zone",
      "config": {
        "labels": {},
        "choices": {
          "text": {
            "type": "Slice",
            "fieldset": "Text",
            "description": "Rich Text Section",
            "icon": "text_fields",
            "non-repeat": {
              "text": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, preformatted, heading1, heading2, heading3, heading4, heading5, heading6, strong, em, hyperlink, image, embed, list-item, o-list-item, o-list-item",
                  "label": "text",
                  "placeholder": "Your content here"
                }
              }
            },
            "repeat": {}
          },
          "quote": {
            "type": "Slice",
            "fieldset": "Quote",
            "description": "A short quote with author's portrait",
            "icon": "add_alert",
            "non-repeat": {
              "quote": {
                "type": "StructuredText",
                "config": {
                  "single": "em",
                  "label": "Quote",
                  "placeholder": "Your quote"
                }
              },
              "name_of_the_author": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph",
                  "label": "Name of the author",
                  "placeholder": "John Doe"
                }
              },
              "portrait_author": {
                "type": "Image",
                "config": {
                  "constraint": {
                    "width": 700,
                    "height": 700
                  },
                  "thumbnails": [
                    {
                      "name": "mobile",
                      "width": 350,
                      "height": 350
                    }
                  ],
                  "label": "Portrait Author"
                }
              }
            },
            "repeat": {}
          },
          "banner_with_caption": {
            "type": "Slice",
            "fieldset": "Banner with caption",
            "description": "Banner with caption and button",
            "icon": "chrome_reader_mode",
            "non-repeat": {
              "image_banner": {
                "type": "Image",
                "config": {
                  "constraint": {
                    "width": null,
                    "height": null
                  },
                  "thumbnails": [],
                  "label": "Image Banner"
                }
              },
              "title_of_banner": {
                "type": "StructuredText",
                "config": {
                  "multi": "heading2",
                  "label": "Title Of banner",
                  "placeholder": "My title of banner"
                }
              },
              "description": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph",
                  "label": "Description",
                  "placeholder": "My description"
                }
              },
              "button_label": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, preformatted, heading1, heading2, heading3, heading4, heading5, heading6, strong, em, hyperlink, image, embed, list-item, o-list-item, o-list-item",
                  "label": "Button label",
                  "placeholder": "Click Here"
                }
              },
              "button_link": {
                "type": "Link",
                "config": {
                  "label": "Button Link",
                  "placeholder": "Select the link"
                }
              }
            },
            "repeat": {}
          },
          "image_gallery": {
            "type": "Slice",
            "fieldset": "Image Gallery",
            "description": "Image Gallery with a title and a caption for each image",
            "icon": "photo_library",
            "non-repeat": {
              "name_of_the_gallery": {
                "type": "StructuredText",
                "config": {
                  "single": "heading2",
                  "label": "Name of the gallery",
                  "placeholder": "My beautiful paintings"
                }
              }
            },
            "repeat": {
              "image_captions": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph",
                  "label": "Image captions",
                  "placeholder": "Images captions"
                }
              },
              "gallery_image": {
                "type": "Image",
                "config": {
                  "constraint": {
                    "width": null,
                    "height": null
                  },
                  "thumbnails": [],
                  "label": "Gallery Image"
                }
              }
            }
          }
        }
      }
    }
  },
  "Meta": {
    "meta_description": {
      "type": "Text",
      "config": {
        "label": "Meta description"
      }
    },
    "meta_title": {
      "type": "Text",
      "config": {
        "label": "Meta title"
      }
    },
    "uid": {
      "type": "UID",
      "config": {
        "label": "Slug"
      }
    }
  }
}
```

**Comment by jodiedoubleday** [comment]
(this is a guess)
I think its your `"labels": {},`
in my schema the labels represents the labels of each slice (or slice name) for example...
```"labels" : {
          "accordion" : [ ],
          "card_deck" : [ ],
          "contact" : [ ],
          "map" : [ ],
          "text" : [ ]
        },```

try changing yours to...
```"labels" : {
          "text" : [ ],
          "quote" : [ ],
          "banner_with_caption" : [ ],
          "image_gallery" : [ ]
        },```

🤞

**Comment by jodiedoubleday** [comment]
@hades200082 did this help?

**Comment by hades200082** [comment]
Hi @jodiedoubleday , thanks for the reply but I think you missed what I was reporting.

I'm dealing with the "Link" element in Prismic.

When querying a Link element that is set to "link_type" "Document" if you include the "url" field in the GraphQL query it results in an error.

```
query MyQuery {
  allPrismicPage {
    nodes {
      uid
      type
      data {
        cta_link {
          link_type
          url
        }
      }
    }
  }
}
```

The above query results in an error. The one below does not. Moreover, the "raw" property returns JSON which includes the "url" property from Prismic without causing an error.

This suggests that the mapping of data from Prismic to the url property of the query is failing in the plugin somewhere along the lines.

```
query MyQuery {
  allPrismicPage {
    nodes {
      uid
      type
      data {
        cta_text
        cta_link {
          link_type
          raw
        }
      }
    }
  }
}
```

For the time being, I've worked around my issue by using "raw" directly. I reported the issue here so that it might be fixed in a future version.

**Comment by jodiedoubleday** [comment]
Apologies, yup completely answered the wrong thing.

Can you send over a copy of your gatsby-config.js? (edit out any repo names if you want)

**Comment by RobinHerzog** [comment]
Hello everyone
Does anyone has a solution?

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
