### ISSUE TITLE
gatsby-source-prismic - invalid plugin options

### ISSUE THREAD

**Issue by elliotkidd** [prismicio/prismic-gatsby#303]
I get the error below when trying to run a build. Working in dev is fine.

```
gatsby-source-prismic - invalid plugin options

Failed to validate error Error [ValidationError]: child "type" fails because ["type" must be one of [GRAPHQL, CONFIG, WEBPACK, PLUGIN]]
    at Object.exports.process (/Users/elliotkidd/projects/kick-snare/node_modules/@hapi/joi/lib/errors.js:202:19)
    at internals.Object._validateWithOptions (/Users/elliotkidd/projects/kick-snare/node_modules/@hapi/joi/lib/types/any/index.js:763:31)
    at internals.Object.validate (/Users/elliotkidd/projects/kick-snare/node_modules/@hapi/joi/lib/types/any/index.js:797:21)
    at constructError (/Users/elliotkidd/projects/kick-snare/node_modules/gatsby-cli/lib/structured-errors/construct-error.js:52:32)
    at Reporter.error (/Users/elliotkidd/projects/kick-snare/node_modules/gatsby-cli/lib/reporter/reporter.js:135:59)
    at Reporter.panic (/Users/elliotkidd/projects/kick-snare/node_modules/gatsby-cli/lib/reporter/reporter.js:75:34)
    at Object.webhookBody [as panic] (/Users/elliotkidd/projects/kick-snare/node_modules/gatsby/src/utils/api-runner-node.js:201:16)
    at Object.exports.sourceNodes (/Users/elliotkidd/projects/kick-snare/node_modules/gatsby-source-prismic/src/gatsby-node.ts:160:8)
    at runAPI (/Users/elliotkidd/projects/kick-snare/node_modules/gatsby/src/utils/api-runner-node.js:460:22)
    at Promise.catch.decorateEvent.pluginName (/Users/elliotkidd/projects/kick-snare/node_modules/gatsby/src/utils/api-runner-node.js:611:13)
    at Promise._execute (/Users/elliotkidd/projects/kick-snare/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/elliotkidd/projects/kick-snare/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/elliotkidd/projects/kick-snare/node_modules/bluebird/js/release/promise.js:103:10)
    at /Users/elliotkidd/projects/kick-snare/node_modules/gatsby/src/utils/api-runner-node.js:609:16
    at tryCatcher (/Users/elliotkidd/projects/kick-snare/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/elliotkidd/projects/kick-snare/node_modules/bluebird/js/release/reduce.js:166:18) {
  isJoi: true,
  details: [
    {
      message: '"type" must be one of [GRAPHQL, CONFIG, WEBPACK, PLUGIN]',
      path: [Array],
      type: 'any.allowOnly',
      context: [Object]
    }
  ],
  _object: {
    context: {},
    value: undefined,
    type: 'string',
    path: [],
    branch: [ undefined ],
    failures: [Function: failures],
    pluginName: 'gatsby-source-prismic',
    text: 'There was an error',
    level: 'ERROR',
    stack: [],
    docsUrl: 'https://gatsby.dev/issue-how-to'
  },
  annotate: [Function (anonymous)]
}
```

What is `child "type"` that is causing this?

In my gatsby.config I have:

```
{
	resolve: 'gatsby-source-prismic',
	options: {
		repositoryName: process.env.PRISMIC_REPOSITORY_NAME,
		accessToken: process.env.PRISMIC_ACCESS_TOKEN,
		linkResolver: ({ node, key, value }) => (post) => `/${post.uid}`,
		schemas: {
			blog: require('./src/schemas/blog.json'),
		},
	},
},
```

**Comment by PaulinaVPG** [comment]
Returning to Version 3.3.0 removed the error for me. At least temporarily :)

**Comment by elliotkidd** [comment]
hmm, that hasn't seemed to help in my case.

**Comment by tudor2004** [comment]
I'm having the same problem, tried version 3.3.0 and 3.2.1. Any suggestions?

**Comment by tudor2004** [comment]
I managed to solve my issue, it was an error in my config.

**Comment by elliotkidd** [comment]
Could you share your config @tudor2004? I've probably done the same thing...

**Comment by tudor2004** [comment]
Yes, so I had this in the config:
```
{
      resolve: "gatsby-source-prismic",
      options: {
          repositoryName: "myrepo",
          accessToken: `${process.env.API_KEY}`,
          linkResolver: () => prismicLinkResolver,
          htmlSerializer: () => prismicHtmlSerializer,
    },
    schemas: {
       // all the schemas here
    }
}
```

instead of this:

```
{
      resolve: "gatsby-source-prismic",
      options: {
          repositoryName: "myrepo",
          accessToken: `${process.env.API_KEY}`,
          linkResolver: () => prismicLinkResolver,
          htmlSerializer: () => prismicHtmlSerializer,
          schemas: {
             // all the schemas here
          }
    }
}
```

notice the "schema" block not being inside the "options" block.

**Comment by ClemensMoosbrugger** [comment]
I have the  same problem when i try to deploy on Netlify

**Comment by bndnio** [comment]
I ran into this issue when migrating from the `@prismico/gatsby-source-prismic-graphql` plugin to this one. In the process of migrating my htmlSerializer.js file from es6 to CommonJS (because of where it's now used), I mistakenly exported it as:
```js
exports = function htmlSerializer(type, element, content, children) {
    ...
}
```

instead of
```js
module.exports = function htmlSerializer(type, element, content, children) {
    ...
}
```

So it turned out to be a config problem on my part because I'm a lil rusty with CommonJS 😅 Changing my default exports to the latter resolved my issue.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!

**Comment by skrbnv** [comment]
FYI, missing .env.production during build can cause this too :)

**Comment by luckhole007** [comment]
Invalid plugin options for "gatsby-source-prismic":

- gatsby-source-prismic(ellipsis-drive) - JSON model for "episode" is missing. If the Custom Type is no longer in use, you
 may provide "{}" as the JSON model.
- gatsby-source-prismic(ellipsis-drive) - JSON model for "article_cta" is missing. If the Custom Type is no longer in use,
 you may provide "{}" as the JSON model.
