### ISSUE TITLE
Error when building schema

### ISSUE THREAD

**Issue by dnlmzw** [prismicio/prismic-gatsby#457]
### Versions

- gatsby-source-prismic: ^4.2.0
- gatsby-plugin-prismic-previews: ^4.2.0
- node: v12.16.3

I get the following error in my console, when trying to start my development server. I've tried reinstalling the node_modules folder and have cleared the gatsby cache. Not sure where to go from here:

```
Missing onError handler for invocation 'building-schema', error was 'Error: Type with name "GatsbyImageLayout" does not
exists'. Stacktrace was 'Error: Type with name "GatsbyImageLayout" does not exists
    at SchemaComposer.get
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/TypeStorage.js:44:13)
    at ThunkComposer._thunk
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/TypeMapper.js:585:34)
    at ThunkComposer.get ofType [as ofType]
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/ThunkComposer.js:20:34)
    at getTypeNode
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/definitionNode.js:265:28)
    at getTypeNode
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/definitionNode.js:265:12)
    at /Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/definitionNode.js:296:18
    at Array.map (<anonymous>)
    at getArgumentsDefinitionNodes
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/definitionNode.js:294:19)
    at /Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/definitionNode.js:326:18
    at Array.map (<anonymous>)
    at getFieldDefinitionNodes
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/definitionNode.js:315:21)
    at getObjectTypeDefinitionNode
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/definitionNode.js:40:13)
    at ObjectTypeComposer.getType
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/ObjectTypeComposer.js:700:76)
    at getGraphQLType
(/Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/utils/typeHelpers.js:164:17)
    at /Users/danielmierzwinski/Websites/ö/inpay/node_modules/graphql-compose/lib/SchemaComposer.js:167:79
    at Array.forEach (<anonymous>)'
```

<details open>
<summary>Additional Details</summary>
```
"dependencies": {
"@gatsbyjs/reach-router": "^1.3.6",
    "@inlet/react-pixi": "^5.0.3",
    "@reach/router": "^1.3.4",
    "@sentry/gatsby": "^5.27.3",
    "@sentry/react": "^5.21.1",
    "bootstrap": "^4.5.0",
    "classnames": "^2.2.6",
    "core-js": "^2.6.5",
    "dotenv": "^8.2.0",
    "framer-motion": "^2.9.4",
    "gatsby": "^3.14.2",
    "gatsby-link": "^3.14.0",
    "gatsby-plugin-config": "^1.0.7",
    "gatsby-plugin-csp": "^1.1.3",
    "gatsby-plugin-google-tagmanager": "^3.14.0",
    "gatsby-plugin-manifest": "^3.14.0",
    "gatsby-plugin-netlify-headers": "^1.0.1",
    "gatsby-plugin-offline": "^4.14.0",
    "gatsby-plugin-polyfill-io": "^1.1.0",
    "gatsby-plugin-prismic-previews": "^4.2.0",
    "gatsby-plugin-react-helmet": "^4.14.0",
    "gatsby-plugin-robots-txt": "^1.6.10",
    "gatsby-plugin-sass": "^4.14.0",
    "gatsby-plugin-sharp": "^3.14.1",
    "gatsby-plugin-sitemap": "^4.10.0",
    "gatsby-plugin-transition-link": "^1.20.5",
    "gatsby-react-router-scroll": "^4.14.0",
    "gatsby-source-filesystem": "^3.14.0",
    "gatsby-source-prismic": "^4.2.0",
    "gatsby-transformer-sharp": "^3.14.0",
    "gsap": "^3.4.2",
    "intersection-observer": "^0.11.0",
    "lodash": "^4.17.19",
    "lodash.snakecase": "^4.1.1",
    "node-sass": "^4.14.1",
    "objectFitPolyfill": "^2.3.0",
    "pixi.js": "^5.3.3",
    "pixi.js-legacy": "^5.3.3",
    "prismic-reactjs": "^1.3.1",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-countup": "^4.3.3",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0",
    "react-hot-loader": "^4.13.0",
    "react-intersection-observer": "^8.30.1",
    "react-is": "^17.0.2",
    "react-visibility-sensor": "^5.1.1",
    "styled-components": "^5.1.1",
    "whatwg-fetch": "^3.4.1"
}
```
</details>

**Comment by angeloashmore** [comment]
Hey @dnlmzw, glad you found the fix. `gatsby-plugin-image` was recently updated (`v1.14.1`) and is now required to be added to `gatsby-config.js`.

Our docs are being updated to include this. Thanks!
